### ISSUE TITLE
It's not working for me

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#1]
hey I don't really know much about this, I just follwed the guides on both repositories like copying and pasting files but it's not working or maybe I have to enable it someway? Sorry if I'm missing something this is a bit of a mess for my brain

![image](https://github.com/user-attachments/assets/a13c0c45-f133-4319-b201-58a990e7e793)

![image](https://github.com/user-attachments/assets/429306f4-f034-45b0-933f-0af3f4b363b9)

**Comment by Octur1s** [comment]
I got it to work by putting second_sidebar.uc.mjs and the second_sidebar folder both in the JS folder

File structure

```
Chrome
└── JS
    ├── second_sidebar.uc.mjs       (File)
    └── second_sidebar              (Folder)

```

**Comment by duckaleuze** [comment]
thanks it worked!
