### ISSUE TITLE
Toolbar Improvements

### ISSUE THREAD

**Issue by Octur1s** [aminought/firefox-second-sidebar#10]
Hello! I have some suggestions for adjusting the toolbar that I think would be good, I've mocked up examples for clarity

 - The forward button should be hidden unless forward navigation is possible. This way the toolbar has some extra room for the page title. Edge for example has this option for reference.
 
 - The page title should have `text-overflow: ellipsis;` so it doesn't just cut off. This may require `display: inline-block` to get it to work as well, and some `margin-top: ` adjustment to recenter the title vertically.
 
 Edge setting: 
 
![image](https://github.com/user-attachments/assets/ab5e63fc-a6c3-4ce8-9224-6e71bb0c2a96)

Example: 
Top - With adjustments
Bottom - Current

![image](https://github.com/user-attachments/assets/a7348f5c-355c-4fd4-be37-baf9fe0f0f51)

**Comment by aminought** [comment]
Added ellipsis in 089656ae4b71a6ac4dbef76f304c3b09c9d91c65.

**Comment by aminought** [comment]
> * The forward button should be hidden unless forward navigation is possible.

Why shouldn't this logic apply to the back button as well?

**Comment by Octur1s** [comment]
On reconsideration, I realize that hiding buttons, even though it does help clear up space, as a baseline is likely a bad UX decision. 

I think it should be left as is then. But thanks for adding the ellipsis!

**Comment by aminought** [comment]
Added options to configure the auto-hide of the "back" and "forward" buttons: #19.
