### ISSUE TITLE
Addition Toolbar Actions

### ISSUE THREAD

**Issue by Octur1s** [aminought/firefox-second-sidebar#11]
I would be nice to be able to open the sidebar page in a normal tab or copy it's URL quickly. This could be accomplished via a toolbar button similar to Edge's sidebar. This would be useful since URL of the sidebar is not always the same as the one used to create web panel due to page navigation.

A good icon for the button could be `chrome://devtools/skin/images/more.svg`

Example:

![image](https://github.com/user-attachments/assets/da12be31-0540-454f-9328-90ded2dacc70)

**Comment by guigirl42** [comment]
This is yet another lovely enhancement, thanks for doing it :heart_decoration:
