### ISSUE TITLE
Option to request Mobile Site

### ISSUE THREAD

**Issue by Octur1s** [aminought/firefox-second-sidebar#12]
Thank you again for this project, I have just one more suggestion for the time being - 

I think it would be nice to have the option to open web panels in their mobile versions since some sites have layouts that are tailored to vertical screens. I believe this can be accomplished via a custom user-agent to make the site think its being loaded on a mobile device.

Zen and Edge have this functionality for reference.

Example for setting:

![Untitled](https://github.com/user-attachments/assets/b3428a9c-2997-4d10-b490-84097bab5a54)

Thanks!

**Comment by aminought** [comment]
Added option to use mobile user agent in 64c7776a853a2411f13377de600130cc00629ee1.
