### ISSUE TITLE
Feature request: Change Zoom Level (+ context menu suggestions)

### ISSUE THREAD

**Issue by KiKaraage** [aminought/firefox-second-sidebar#13]
As someone with HD resolution monitor, 100% zoom is usually too big for me on certain sites, like Twitter or YouTube; and this shows even more when I use those sites as web panels/sidebar.

It can be a slider shows up behind a button, but it could also be two buttons for zoom in & zoom out behind a Menu button.

I imagined the Menu can be structured like this:
- Mute site
- Unload site
- Copy current link
- Load mobile version / Load desktop version*
- _(separator)_
- Zoom in / Increase zoom level
- Zoom out / Decrease zoom level
- Reset zoom level
- _(separator)_
- Site panel settings
- Remove site from panel

(*different text shown, depend on which useragent is used currently)

**Comment by guigirl42** [comment]
Yes pls, being able to zoom each web panel in / out would be a nice enhancement. If not with explicit UI controls, at least via `Ctrl`+WheelScroll like on ordinary tabs. Thanks.

**Comment by aminought** [comment]
Now you can zoom your web panels! #29
![image](https://github.com/user-attachments/assets/a1a07fbb-6b9d-4161-9534-ef113ed24bea)

**Comment by guigirl42** [comment]
> Now you can zoom your web panels

Oh wow! _Exciting_. 

How do we _get_ this pls? https://github.com/aminought/firefox-second-sidebar is still showing `v1.1` from 3 weeks ago... do i just keep checking back here each few hours? On that, how do we actually _do_ updates; i assume we don't so much "update", as just repeat the initial installation, which then in effect gives us the new version?

**Comment by aminought** [comment]
> > Now you can zoom your web panels
> 
> Oh wow! _Exciting_.
> 
> How do we _get_ this pls? https://github.com/aminought/firefox-second-sidebar is still showing `v1.1` from 3 weeks ago... do i just keep checking back here each few hours? On that, how do we actually _do_ updates; i assume we don't so much "update", as just repeat the initial installation, which then in effect gives us the new version?

Thank you! To get the latest version, you can simply download the files from the main branch by clicking "Code" and then "Download ZIP". I release new versions quite randomly when there are enough changes.

**Comment by guigirl42** [comment]
What a hero you are! It works _beautifully_. Thank you so much for this transformational gift to the community  💜
