### ISSUE TITLE
[Feature request] add a border around the web panel

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#14]
I think this is a decent UI idea because it provides visual feedback on the active web panel and its size, like Zen browser's web panel, I made this little concept:

![web panel concept](https://github.com/user-attachments/assets/9ce03b48-eeb8-4a2f-9c5f-dde8d0b5bdf8)

it would be nice since custom userchrome themes can be compatible with this concept of an adaptive color around the web panels

Zen's web panel for reference: 

![image](https://github.com/user-attachments/assets/81664f6a-24ad-4b8e-b5f1-99028defc119)

this is a great example since I chose a very light color just for the concept

**Comment by aminought** [comment]
Hi! Actually, there is a border around the web panel, but its color relies on Firefox CSS-variables. If you want to use this in Zen, you need customization. I heard Zen has no problems with customization. :wink:

**Comment by duckaleuze** [comment]
First of all thanks for this great project, I've absolutely loved it; you are a legend man! I know there's a border but I think it is a bit faint because with dark themes you cannot really see the outline of the web panel, at least not so clearly as Zen's one. I mainly use vanilla Firefox btw

![image](https://github.com/user-attachments/assets/329008bc-c849-41ae-ada6-0bfa827a915d)

**Comment by aminought** [comment]
Thank you! The problem is that I'm actually a backend developer, and CSS is pretty hard for me. :smile:  Yes, there are some problems with the display now, I will try to take time to fix it.

**Comment by aminought** [comment]
Actually, it's not the styles that are causing the problem, it's the theme you are using. I have checked with other themes and found that the outline is only visible if the theme supports it. Therefore, I believe that this issue has been resolved.
