### ISSUE TITLE
I still get this weird extra scrollbar spaces (right one and bottom one)

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#16]
![image](https://github.com/user-attachments/assets/8fcfaf9d-17a3-4f37-a998-c30cf0e4af61)

**Comment by aminought** [comment]
Perhaps I have a suggestion. Could you try toggle the setting `General -> Browsing -> Always show scrollbars` in `about:preferences`?

**Comment by aminought** [comment]
I'm sorry for the inconvenience, fixed it with CSS.

**Comment by duckaleuze** [comment]
it came back to life D:

<img width="856" height="1079" alt="Image" src="https://github.com/user-attachments/assets/73967aec-5869-49e3-8d83-9e9882029264" />
