### ISSUE TITLE
[Bug] Sidebar gets injected in "popup" type windows

### ISSUE THREAD

**Issue by emvaized** [aminought/firefox-second-sidebar#17]
Currently the script injects the sidebar in windows with type `popup`: 
![illustration](https://github.com/user-attachments/assets/ac47b4e7-4193-4094-addb-5470a97c1b69) 

This should be avoided, as the main purpose of this window type is to not have any browser controls, such as address bar, tab bar, etc. 

I believe that in CSS such windows could be queried by checking if the `:root` has `chromehidden` attribute equal to anything other than `""`

**Comment by aminought** [comment]
Added an option to the settings to hide the sidebar in popup windows instead of hiding it unconditionally (#28):

![image](https://github.com/user-attachments/assets/d920fa1a-4626-4b6a-829a-6b3609234986)
