### ISSUE TITLE
[Request] Option to enable mobile view for the web panel

### ISSUE THREAD

**Issue by emvaized** [aminought/firefox-second-sidebar#18]
It would be awesome to have a setting for each web panel to apply mobile client to the page, because many pages open in their regular desktop view and doesn't adapt well to the small available width. 

Such option exists in the Floorp browser: 
![illustration](https://github.com/user-attachments/assets/a68c7250-9c12-406b-a1a7-2b9bcad2a76d)

**Comment by aminought** [comment]
Duplicate of #12.
