### ISSUE TITLE
[Request] Show web panel's URL when hovering the icon

### ISSUE THREAD

**Issue by emvaized** [aminought/firefox-second-sidebar#21]
Showing web panel's URL as a tooltip on hover will help to distinguish between web panels with similar or the same favicons: 

![illustration](https://github.com/user-attachments/assets/7d18116c-064f-44b8-991d-de971ed4858c) 

It could be some basic tooltip, as by just setting the `title` [attribute](https://www.w3schools.com/tags/att_global_title.asp).

**Comment by guigirl42** [comment]
Oh fabulous; thank you! 🎉
