### ISSUE TITLE
[Bug] sidebar panels randomly blanking out completely

### ISSUE THREAD

**Issue by ThinkSalat** [aminought/firefox-second-sidebar#25]
The web panels seem to randomly start showing like a black overlay over the panels. The actual content is still there as the moment I click to open a panel, the webpanel shows up, but then immediately a black overlay covers it up like in the screenshot below

![image](https://github.com/user-attachments/assets/dd9a8e35-2049-4a31-b166-2097dc84a0eb)

**Comment by aminought** [comment]
Thank you for your feedback. I am aware of the issue, but I have not yet been able to find a solution that would not affect performance.

**Comment by aminought** [comment]
Fixed it in e293d62b, but I'm not sure how this will affect performance.
