### ISSUE TITLE
Enhancement Request | Allow user to choose second-sidebar's width.

### ISSUE THREAD

**Issue by guigirl42** [aminought/firefox-second-sidebar#26]
Hi. As many others have already said, your work is brilliant & i'd also like to gratefully thank you for it. 

In my Floorp the Sidebar width is ~`35 px`, whereas in your project it is ~`50 px`. Is it possible pls to have an option to narrow your one to be similar to Floorp's? 

If inconvenient for you, or even not possible, to provide an actual UI setting for it, pls could you point me to which CSS file is currently controlling it, so i can try manually editing it? I examined several of them but couldn't find the right one.

Best regards.

**Comment by emvaized** [comment]
`#sidebar-2-main` is the CSS selector for the sidebar panel to be used in `userChrome.css`

**Comment by guigirl42** [comment]
> #sidebar-2-main

Oh thank you! I'm happy to say this has done the trick, in my `userChrome.css`:
```
#sidebar-2-main {
  width: 30px !important; 
}
```
Now it looks much better IMO, as well as ofc providing the corresponding extra width to the actual webpages.

**Comment by aminought** [comment]
Added option to change sidebar-main width (#30):

![image](https://github.com/user-attachments/assets/7c671361-e721-409d-a691-b4d51d279eb9)

**Comment by guigirl42** [comment]
> Added option to change sidebar-main width

Thanks very much for doing this. Unfortunately, even the "Tiny" option is still too wide for me, so i have chosen to continue using the recent addition to my `userChrome.css` as [above](https://github.com/aminought/firefox-second-sidebar/issues/26#issuecomment-2495873125).

**Comment by guigirl42** [comment]
@aminought I just wish to thank & congratulate you for the brand new `v1.2.1`. It's really superb! The additional panel settings are marvellous, & now my CSS above is certainly redundant; by the following combo [pic] my panel is now 28px wide, still with full functionality & visibility, i love it. Really great work by you. :heart_decoration: 

![image](https://github.com/user-attachments/assets/c4ea717b-9fd6-4d81-b065-1ccbaa1a187c)

I was just about to post the above, but had this quick crazy idea. As well as the button position options of `top` & `bottom`, is it doable to have a third option for `centred` pls? :woman_shrugging:
