### ISSUE TITLE
Cropped url bar and small horizontal scrollbar

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#3]
the url bar is a bit cropped and there are weird tiny horizontal scrollbars on the sidebar

https://github.com/user-attachments/assets/7f9cfad8-c2e5-4132-9ed8-352deca5f8ad

**Comment by dimdamin** [comment]
You can try modify **second_sidebar.uc.mjs**
``` Diff
    #tabbrowser-tabbox {
-      z-index: 4;
+      z-index: auto;
    }
```
