### ISSUE TITLE
Context menu item

### ISSUE THREAD

**Issue by Octur1s** [aminought/firefox-second-sidebar#4]
Hello!

First off, thanks so much for creating this - I've wanted a proper sidebar for so long instead of having to sacrifice the bookmarks/history sidebar to load web pages side by side (hoping firefox adds proper split screen someday).

Could you consider adding a context menu item to open links in the sidebar? The idea would be that it would create a new web panel with that link, just like if you added one manually.

Thanks!

![Screenshot 2024-11-07 222052](https://github.com/user-attachments/assets/233ae4ae-cecd-4dad-af9e-709110f2ed28)

**Comment by aminought** [comment]
Thank you for your kind words and the feature request!

Now you can open a page in the sidebar with just two clicks: the plus sign and the "Save" button. The current address will be automatically substituted. Would you prefer to have one click instead of two or something else?

**Comment by Octur1s** [comment]
My use case example would be to open a link that is different from the current address in the sidebar, similar to this extension functionality, this loads the web page in the native sidebar.

https://github.com/user-attachments/assets/a7bdfb2b-c227-482b-9243-9acd4f3af6da

**Comment by aminought** [comment]
@Octur1s Hello! I've added context menu item "Open Link in Second Sidebar" in a29ab52db9c094a36ba8678f280b30836e3c5d40.
