### ISSUE TITLE
Option to choose which side second sidebar shows up on

### ISSUE THREAD

**Issue by ThinkSalat** [aminought/firefox-second-sidebar#8]
Hi, LOVE the work you've done with this. It seems like it's hard coded to show up on the right side. What kind of work would it require to be able to use it on the left side instead? I'm currently using Floorp and my setup is Sidebery on the right, web panels on the left. 

Thanks again for sharing this awesome work!

**Comment by aminought** [comment]
Hi. First of all, I need to add some kind of sidebar settings, and then figure out how to implement choosing a side without conflicting with the original sidebar. The least favorite part for me is messing with CSS. 😆 But this feature request is next in the queue for development.

**Comment by ThinkSalat** [comment]
Omg I'd love to help if I can make this happen sooner!

**Comment by aminought** [comment]
In #19, I added sidebar settings, which allow me to add choosing of the side.

**Comment by aminought** [comment]
I have implemented a position change (#22), it takes a little time to test.
@ThinkSalat Please take a look and let me know if this solution is suitable for you.

**Comment by aminought** [comment]
Merged #22 into master.

**Comment by ThinkSalat** [comment]
Nice! Amazing work!
