### ISSUE TITLE
opening a link (from a web panel) in new tab and then closing it makes it impossible to interact with any tab

### ISSUE THREAD

**Issue by duckaleuze** [aminought/firefox-second-sidebar#9]
I installed the webextensions-support userchrome.js and that bug happened (btw extensions work! :D)

https://github.com/user-attachments/assets/fbc38561-bb51-4e54-81ac-9a8f7d5eeca6

**Comment by aminought** [comment]
Updated the branch, please check.

**Comment by duckaleuze** [comment]
fixed! thanks for your great job, this project is awesome
